# General Settings
name: Filippo Scognamiglio
job_title: Android Software Engineer
email: flscogna@gmail.com
description: cat /dev/urandom | tr -dc 'a-z A-Z'
avatar: /assets/avatar.jpg
favicon: /favicon.ico
twitter_handler: your_handler
analytics_code: UA-137354863-1
disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: '' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/filipposcognamiglio90/' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/Swordfish90' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 0
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://swordfish90.github.io"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

